CREATE TABLE `ecs_favourable_activity` (
  `act_id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `act_name` varchar(255) NOT NULL,
  `start_time` int(10) unsigned NOT NULL,
  `end_time` int(10) unsigned NOT NULL,
  `user_rank` varchar(255) NOT NULL,
  `act_range` tinyint(3) unsigned NOT NULL,
  `act_range_ext` varchar(255) NOT NULL,
  `min_amount` decimal(10,2) unsigned NOT NULL,
  `max_amount` decimal(10,2) unsigned NOT NULL,
  `act_type` tinyint(3) unsigned NOT NULL,
  `act_type_ext` varchar(255) NOT NULL,
  `gift` text NOT NULL,
  `sort_order` tinyint(3) unsigned NOT NULL DEFAULT '50',
  `gift_package` blob NOT NULL,
  `evel_type` varchar(150) NOT NULL,
  `is_join_amount` tinyint(1) NOT NULL,
  `gift_range` varchar(765) NOT NULL,
  `gift_range_price` varchar(765) NOT NULL,
  `level_type` varchar(150) NOT NULL,
  `unique_id` varchar(20) NOT NULL COMMENT '唯一标识,对应业务后台',
  `gift_range_ext` varchar(255) DEFAULT NULL,
  `conflict_act` text COMMENT '不以该活动同时进行的活动列表',
  `is_after_discount` tinyint(3) NOT NULL DEFAULT '0' COMMENT '获赠资格是否以折后价格为准',
  `stock_limited` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否限制库存',
  `shipping_free` varchar(10) DEFAULT '0' COMMENT '包邮，1在线支付，2货到付款，1,2在线或货到付款',
  PRIMARY KEY (`act_id`),
  KEY `act_name` (`act_name`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=786 DEFAULT CHARSET=utf8;

