<?php
/**
 * ====================================
 * 品牌调查模型
 * ====================================
 * Author: 9004396
 * Date: 2017-02-17 16:06
 * ====================================
 * Project: new.m.chinaskin.cn
 * File: SurveyModel.class.php
 * ====================================
 */
namespace Cpanel\Model;
use Common\Model\CpanelModel;
use Common\Extend\Time;
use Common\Extend\PhxCrypt;

class CustomerQuerylogModel extends CpanelModel{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $config = C('db_config.1');
        $this->connection = array_merge($config['CONFIG'], array('DB_TYPE' => C('DB_TYPE')));
        $this->tablePrefix = $this->connection['DB_PREFIX'];
        $this->tableName = 'customer_query_log';
    }

    public function filter(&$params){
        if(!empty($params['keyword'])){
            $keyword = trim($params['keyword']);
            $map['_string'] = 'phone="'.PhxCrypt::phxEncrypt($keyword).'" or weixin="'.$keyword.'"';
            $this->where($map);
        }
        if(!empty($params['sort']) &&!empty($params['order'])){
            $this->order($params['sort'].' '.$params['order']);
        }

        return $this;
    }

    //处理查询后的结果
    public function _after_select(&$resultSet,$options){
        foreach($resultSet as $key=>&$val){
            $val['id_num'] = $val['id'];
            $val['phone'] = PhxCrypt::phxDecrypt($val['phone']);
        }
    }


}