<?php
/**
 * ====================================
 * 客服二维码
 * ====================================
 * Author: 9006758
 * Date: 
 * ====================================
 * Project: new.m.chinaskin.cn
 * File: RotateModel.class.php
 * ====================================
 */
namespace Cpanel\Model;
use Common\Model\CpanelModel;
class QrcodeModel extends CpanelModel {

    //客服等级
    private $_kefu_level = array('无等级','A','B','C','D','E','F','G','H','I','J','K','L','M','N');

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $config = C('db_config.1');
        $this->connection = array_merge($config['CONFIG'], array('DB_TYPE' => C('DB_TYPE')));
        $this->tablePrefix = $this->connection['DB_PREFIX'];
        $this->tableName = 'customer_qrcode';
    }

    public function filter(&$params){
        if(!empty($params['keywords'])){
            $keyword = trim($params['keywords']);
            $map['qrcode.real_name'] = $keyword;
            $map['qrcode.job_number'] = $keyword;
            $map['bind.customer_id'] = $keyword;
            $map['_logic'] = 'OR';
            $this->where($map);
        }
        if(!empty($params['sort']) &&!empty($params['order'])){
            $this->order('qrcode.'.$params['sort'].' '.$params['order']);
        }
        $field = 'qrcode.id,qrcode.job_number,qrcode.real_name,qrcode.weixin,qrcode.create_time,qrcode.is_show,qrcode.qrcode_id,';
        $field .= 'qrcode.show_time,qrcode.locked,qrcode.qrcode_type,qrcode.kefu_level,bind.customer_id';
        $this->alias('qrcode')->field($field);

        $this->join("left join __CUSTOMER_QRCODE_BIND__ as bind on qrcode.job_number=bind.job_number");
        return $this;
    }

    public function _after_select(&$resultSet,$options){
        foreach($resultSet as $key=>&$val){
            $locked = $val['locked'];
            $is_show = $val['is_show'];
            $val['kefu_qrcode'] = '<img src="'.$val['kefu_qrcode'].'" style="width:50px; height:50px;">';
            $val['locked'] = '<a href="javascript:;" onclick="lockShow(this,'.$locked.');" data-type="lock" data_id="'.$val['id'].'" class="easyui-linkbutton"><span style="font-size:18px;" class="fa '.($locked==0?'fa-check green':'fa-close red').'"> </span></a>';
            $val['is_show'] = '<a href="javascript:;" onclick="lockShow(this,'.$is_show.');" data-type="show" data_id="'.$val['id'].'" class="easyui-linkbutton"><span style="font-size:18px;" class="fa '.($is_show==0?'fa-check green':'fa-close red').'"> </span></a>';
            $val['kefu_level'] = $this->_kefu_level[$val['kefu_level']];
        }
    }

}